// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPT_JUEGOS.Context;

#nullable disable

namespace TPT_JUEGOS.Migrations
{
    [DbContext(typeof(UsuariosDatabaseContext))]
    [Migration("20251104013644_idAgregadoaUsuario")]
    partial class idAgregadoaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPT_JUEGOS.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CONTRASENA_USUARIO")
                        .HasColumnType("int");

                    b.Property<string>("CORREO_USUARIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EDAD_USUARIO")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE_PERSONA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMBRE_USUARIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
