// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPT_JUEGOS.Context;

#nullable disable

namespace TPT_JUEGOS.Migrations.JuegoDatabase
{
    [DbContext(typeof(JuegoDatabaseContext))]
    [Migration("20251116194552_juegoBD")]
    partial class juegoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPT_JUEGOS.Models.Juego", b =>
                {
                    b.Property<int>("Id_JUEGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_JUEGO"));

                    b.Property<int>("CODIGO_JUEGO")
                        .HasColumnType("int");

                    b.Property<int>("JUEGO_ACTIVO")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE_JUEGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_JUEGO");

                    b.ToTable("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
